name: Test

on:
  schedule:
    # Runs at 1 AM daily
    - cron: "20 * * * *"
  workflow_dispatch:
    inputs:
      workbenches_json:
        description: 'Wrokbenches resources in JSON format'
        required: true
        default: |         
          [
            {
              "resourceGroup": "release-one-wb",
              "resourceSuffix": "release",
              "sku": "EP1",
              "maximumBurst": 5,
              "privateEndpointSupport": false,
              "deployCpdRetryQueue": true
            }
          ]

jobs:
  runtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ toJson(github.event.inputs.workbenches_json) }}
  pass:
    uses: ./.github/workflows/stage-deploy-usecase-infra.yml
    with:
      pass_vars: ${{ github.event.inputs.workbenches_json || 'replace' }}
