name: second

on:
  workflow_call:
    inputs:
      workbenches:
        required: true
        type: string
      usecases:
        required: true
        type: string
jobs:
  runtest:
    runs-on: ubuntu-latest
    steps:

    - name: Run a multi-line script
      run:  |
        MATRIX1=$(echo '${{ inputs.workbenches }}' | jq -c '. | {workbenches: .}')
        MATRIX1=$(echo '${{ inputs.usecases }}' | jq -c '. | {workbenches: .}')
        echo "Matrix generated: $MATRIX1"
        echo "Matrix generated: $MATRIX2"
