name: Test

on:
  #schedule:
    # Runs at 1 AM daily
  #  - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      workbenches_json:
        description: 'Wrokbenches resources in JSON format'
        required: true
        default: |         
          [
            {
              "resourceGroup": "release-one-wb",
              "resourceSuffix": "release",
              "sku": "EP1",
              "maximumBurst": 5,
              "privateEndpointSupport": false,
              "deployCpdRetryQueue": true
            }
          ]

jobs:
  set_json:
    runs-on: ubuntu-latest
    outputs:
      json_out: ${{ steps.set_json_out.outputs.my_variable }}
    steps:
    - name: Generate json
      id: set_json_out
      run: echo "json string" >> $GITHUB_ENV

  passvar:
    uses: ./.github/workflows/second.yml
    with:
      pass_vars: ${{ needs.set_json.outputs.json_out}}
