name: Test

on:
  #schedule:
  # - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: echojson
        run: |
          echo ${{ vars.USECASES_JSON }}

  passvar:
    uses: ./.github/workflows/second.yml
    with:
      usecases: ${{ vars.USECASES_JSON }}