name: Test

on:
  schedule:
   - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      usecases:
        required: true
        type: string
jobs:
  passvar:
    uses: ./.github/workflows/second.yml
    with:
      usecases: ${{ github.event.inputs.usecases || vars.USECASES_JSON }}