name: Test

on:
  schedule:
   - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  passvar:
    uses: ./.github/workflows/second.yml
    with:
      workbenches_json: ${{ vars.WORKBENCHES_JSON }}
      usecases: ${{ vars.WORKBENCHES_JSON }}