name: Test

on:
  schedule:
   - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  passvar:
    uses: ./.github/workflows/second.yml
    with:
      usecases: ${{ toJson(vars.NIGHTLY_USECASES_JSON) }}