name: Test

on:
  schedule:
   - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    run: |
      echo ${{ vars.NIGHTLY_USECASES_JSON }}
  passvar:
    uses: ./.github/workflows/second.yml
    with:
      usecases: ${{ vars.NIGHTLY_USECASES_JSON }}