name: Test

on:
  #schedule:
    # Runs at 1 AM daily
  #  - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      workbenches_json:
        description: 'Wrokbenches resources in JSON format'
        required: true
        default: |         
          [
            {
              "resourceGroup": "release-one-wb",
              "resourceSuffix": "release",
              "sku": "EP1",
              "maximumBurst": 5,
              "privateEndpointSupport": false,
              "deployCpdRetryQueue": true
            }
          ]

jobs:
  passvar:
    uses: ./.github/workflows/second.yml
    with:
      pass_vars: ${{ inputs.workbenches_json}}
